services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  mongodbfactory.api:
    image: ${DOCKER_REGISTRY-}mongodbfactoryapi
    build:
      context: .
      dockerfile: src/MongoDBFactory.API/Dockerfile
    depends_on:
      - mongodb
